### ISSUE TITLE
Criar pasta sobre limpeza e normalização de dados da Câmara dos Deputados

### ISSUE THREAD

**Issue by biamuniz** [gabrielacaesar/python#1]
Vi que há três arquivos sobre "limpeza-e-normalizacao-de-dados" da Câmara dos Deputados. Pode ser bom juntar esses arquivos em uma pasta!

**Comment by gabrielacaesar** [comment]
Oi, @biamuniz! Esses arquivos estão aqui no repositório Python mesmo ou em outro local? Muito obrigada!

**Comment by biamuniz** [comment]
Eita, errei! Estão no repositório R. Abri uma issue lá também [#5](https://github.com/gabrielacaesar/R/issues/5)

**Comment by gabrielacaesar** [comment]
Ok, obrigada!
